dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- name: golang-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: hcbc-backend
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.13
- name: hcbc-hack
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: hcbc-portals
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
